name: UpdateBook
version: ${project.version}
main: com.github.sirokuri_.updatebook.UpdateBook
api-version: 1.15
authors: [46kuri_]
description: LIFE plugin

commands:
  update:
    description: パッチノート
    permission: Update.permission.member

permissions:
  Update.permission.admin:
    default: op
  Update.permission.member:
    default: true
