# コンフィグは主に下記の記述を守って入ればバグることはないです
# 改行して - 'test'と書き込めば次のページの書き込みになります
# カラーコードも使えるので使ってください
# 最新の情報を　- '&2&lLIFESERVER &c&lパッチノートは必ず目を通してください。新要素はすべてこの本に書いてあります'　の後改行して書いてください
# 変更の際は必ず更新日入れてください
# 一つの本につき20ページまでとしそれを超える場合
# Update:
#   1:
#     - '内容'のように上記の数値で分けてください
# /update open 数値[この部分に該当する数値の内容が記入されます
Update:
  JoinMessage1: "&cこの&a[Update※通称パッチノート]\n&cプラグインは&aテクスチャ&cの読み込み時間を\n考慮して作っているので&a&l入室してから7秒後に\n&cメッセージが送信されます"
  JoinMessage2: "&a/update open 数値 &fでパッチノートが開けます"
  WorldOnMessage: "&a[UpdatePlugin] パッチノートが更新されました\n\n&fコマンドは&c/update open 数値&fと入力してください"
  1:
    List:
      - '&2&lLIFESERVER &c&lパッチノートは必ず目を通してください。新要素はすべてこの本に書いてあります'
      - '&4[Fix] &5[2021/04/03] &8ソルウィンドを火山ダンジョンで使えなくしました。それにともないPVEワールドの奥のゲートにてFIX設置しました'
      - '&1[New] &5[2021/04/03] &c火山&8ダンジョン公開!!!!PVEゲートの奥からいけます'
      - '&1[New] &5[2021/04/03] &d&l春レイド&8のドロップ品で交換できるアイテムを追加しました!!!!'
      - '&4[Fix] &5[2021/04/03] &8ソルウィンドのTEXを更新しました。/tex コマンドで表示が変わります'
      - '&1[New] &5[2021/04/02] &d&l春レイド&8最終ボスの特攻アイテム。春のご飯３種類実装しました。 '
      - '&1[New] &5[2021/04/02] &d&l春レイド&8実装しました。&d&l春イベントゲート&8先の村人にて、召喚アイテム交換可能です。'
      - '&4[Fix] &5[2021/04/02] &8Updeteコマンド仕様変更です。&0/update open &8ではなく &0/update open 数値 &8へ仕様変更しました'
      - '&1[New] &5[2021/04/01] &d&l桜ツール&8実装しました。&d&l春イベントゲート&8先のねこちゃんで交換できます。'

  2:
    List:
      - '&2&lLIFESERVER &c&lパッチノートは必ず目を通してください。新要素はすべてこの本に書いてあります'
      - '&4[Fix] &5[2021/03/31] &8BIGAZI SAVIORのTEXがバグっていたので修正しました。商店街ゲート前の村人か商店街のLuckfixという名前の村人で交換できます'
      - '&1[New] &5[2021/03/31] &8どうやら危ない香りがするアイテムが追加されたみたいだ。真相はアジ(イカ)ほどに!?!?!?!?'
      - '&1[New] &5[2021/03/31] &8spawnにLIFE鯖庁舎を作成しました！相談窓口・要望窓口等があり、アクセスは/spawnと打った後、右上方向に進み、右方向に曲がるだけ！'
      - '&4[Fix] &5[2021/03/31] &8PVEにおける耐性5のモブが永久に倒せないバグがあったので耐性5を耐性4に落としました'
      - '&4[Fix] &5[2021/03/31] &8温泉リクエスト申請用紙の説明文を一部変更しました'
      - '&4[fix] &5[2021/03/31] &8温泉リクエストボックスとその中身及び申請用紙が消えたので再申請お願いします。BOXは再設置しました'
      - '&4[fix] &5[2021/03/30] &8ホルダー系のアイテムをシュルカーからレコードに変更、又TEXも募集中'
      - '&4[Fix] &5[2021/03/29] &8ソルウィンドとソルウィンド改にそれぞれ2種のテクスチャ追加。テクスチャ製作者には帰宅後チケット付与します'
      - '&1[New] &5[2021/03/28] &8このPluginができたので動画化しました https://youtu.be/DaV2cMEqlsU'
      - '&4[fix] &5[2021/03/27] &8TTオープンワールドのラグさの主な原因の発光を削除したことでLAG解消、又攻撃時のスキルを幾つか変更し、戦いやすくなりました。'
      - '&4[fix] &5[2021/03/27] &8デッドラインの不可解KILLを修正'
      - '&3[update] &5[2021/03/27] &8シュルカーボックスを置かなくても右クリックで開けるようになりました。'
      - '&3[update] &5[2021/03/27] &8共有TTにオープンワールドの狩場を設置しました。原初の素材となる5種のmobの強化及び超強化版が沸きます。TTと違って順番待ちがないぞ'
      - '&c[balance] &5[2021/03/27] &8ZEZEDOWN仕様変更飛距離がやや落ちました'
      - '&1[New] &5[2021/03/27] &8ソルウィンド実装上級ダンジョンの村人にて入手できます。ソルウィンド・改 実装上級ダンジョンの村人にて入手できます'